"""initial schema

Revision ID: 4ed39f5fa6d0
Revises: 
Create Date: 2026-09-22 23:02:51.567390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4ed39f5fa6d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_records',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distinct_user_count', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_records_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_records_last_seen'), ['last_seen'], unique=False)

    op.create_table('schools',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('allowlisted_cidrs', sa.JSON(), nullable=False),
    sa.Column('max_concurrent_from_ip', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_region'), ['region'], unique=False)

    op.create_table('topics',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('ibo_weight', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=True)

    op.create_table('ip_records',
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_count', sa.Integer(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('distinct_user_count', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('is_allowlisted', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_datacenter', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ip_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_records_ip_address'), ['ip_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_ip_records_is_allowlisted'), ['is_allowlisted'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_records_is_blocked'), ['is_blocked'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_records_last_seen'), ['last_seen'], unique=False)

    op.create_table('topic_translations',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'locale', name='uq_topic_locale')
    )
    with op.batch_alter_table('topic_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_translations_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_translations_topic_id'), ['topic_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('avatar_seed', sa.String(length=32), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('peak_rating', sa.Integer(), nullable=False),
    sa.Column('rated_contests', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_ip', sa.String(length=64), nullable=True),
    sa.Column('registration_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_registration_fingerprint'), ['registration_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_registration_ip'), ['registration_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('daily_activity',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('seconds_active', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_user_day')
    )
    with op.batch_alter_table('daily_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_activity_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_activity_user_id'), ['user_id'], unique=False)

    op.create_table('exams',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title_i18n', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results_visible_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('is_rated', sa.Boolean(), nullable=False),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('shuffle_statements', sa.Boolean(), nullable=False),
    sa.Column('allow_backtracking', sa.Boolean(), nullable=False),
    sa.Column('show_feedback_immediately', sa.Boolean(), nullable=False),
    sa.Column('passing_percent', sa.Float(), nullable=True),
    sa.Column('scoring_curve', sa.JSON(), nullable=True),
    sa.Column('anticheat_policy', sa.JSON(), nullable=False),
    sa.Column('allowed_grades', sa.JSON(), nullable=False),
    sa.Column('allowed_school_ids', sa.JSON(), nullable=False),
    sa.Column('registration_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_closes_at'), ['closes_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_opens_at'), ['opens_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_exams_status'), ['status'], unique=False)

    op.create_table('login_events',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_attempted', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_email_attempted'), ['email_attempted'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('source_ref', sa.String(length=200), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('is_official_ibo', sa.Boolean(), nullable=False),
    sa.Column('template_of_id', sa.Integer(), nullable=True),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('scoring_curve', sa.JSON(), nullable=True),
    sa.Column('answer_spec', sa.JSON(), nullable=True),
    sa.Column('estimated_seconds', sa.Integer(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('discrimination', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_of_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_is_official_ibo'), ['is_official_ibo'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_source_ref'), ['source_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_source_year'), ['source_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic_id'), ['topic_id'], unique=False)

    op.create_table('topic_mastery',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('questions_seen', sa.Integer(), nullable=False),
    sa.Column('statements_seen', sa.Integer(), nullable=False),
    sa.Column('statements_correct', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('points_possible', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('recent_accuracy', sa.Float(), nullable=False),
    sa.Column('avg_seconds', sa.Float(), nullable=False),
    sa.Column('cohort_accuracy', sa.Float(), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic_mastery')
    )
    with op.batch_alter_table('topic_mastery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_mastery_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_mastery_user_id'), ['user_id'], unique=False)

    op.create_table('user_device_links',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_user_device')
    )
    with op.batch_alter_table('user_device_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_device_links_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_device_links_user_id'), ['user_id'], unique=False)

    op.create_table('user_ip_links',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ip_address', name='uq_user_ip')
    )
    with op.batch_alter_table('user_ip_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_ip_links_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_ip_links_user_id'), ['user_id'], unique=False)

    op.create_table('attempts',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('question_order', sa.JSON(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('rating_before', sa.Integer(), nullable=True),
    sa.Column('rating_after', sa.Integer(), nullable=True),
    sa.Column('rating_delta', sa.Integer(), nullable=True),
    sa.Column('performance', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('timezone_offset', sa.Integer(), nullable=True),
    sa.Column('screen', sa.String(length=40), nullable=True),
    sa.Column('seen_ips', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('focus_losses', sa.Integer(), nullable=False),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_is_flagged'), ['is_flagged'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_rank'), ['rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('exam_access_denials',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rule', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('overridden_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overridden_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_access_denials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_access_denials_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_access_denials_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_access_denials_rule'), ['rule'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_access_denials_user_id'), ['user_id'], unique=False)

    op.create_table('exam_access_grants',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('waived_rules', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'user_id', name='uq_exam_access_grant')
    )
    with op.batch_alter_table('exam_access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_access_grants_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_access_grants_user_id'), ['user_id'], unique=False)

    op.create_table('exam_enrollments',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('seat_code', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'user_id', name='uq_exam_enrollment')
    )
    with op.batch_alter_table('exam_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_enrollments_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_enrollments_user_id'), ['user_id'], unique=False)

    op.create_table('exam_sections',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_i18n', sa.JSON(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_sections_exam_id'), ['exam_id'], unique=False)

    op.create_table('exam_statistics',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=False),
    sa.Column('mean_score', sa.Float(), nullable=False),
    sa.Column('median_score', sa.Float(), nullable=False),
    sa.Column('stdev_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('histogram', sa.JSON(), nullable=False),
    sa.Column('topic_breakdown', sa.JSON(), nullable=False),
    sa.Column('question_stats', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=400), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_statistics_exam_id'), ['exam_id'], unique=True)

    op.create_table('figures',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('in_appendix', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('figures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_figures_question_id'), ['question_id'], unique=False)

    op.create_table('question_reviews',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_reviews_question_id'), ['question_id'], unique=False)

    op.create_table('question_translations',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('general_explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'locale', name='uq_question_locale')
    )
    with op.batch_alter_table('question_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_translations_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_translations_question_id'), ['question_id'], unique=False)

    op.create_table('statements',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=4), nullable=False),
    sa.Column('is_true', sa.Boolean(), nullable=False),
    sa.Column('pin_position', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statements_question_id'), ['question_id'], unique=False)

    op.create_table('attempt_events',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_events_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_events_kind'), ['kind'], unique=False)

    op.create_table('cheat_flags',
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('rule', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cheat_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cheat_flags_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheat_flags_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheat_flags_rule'), ['rule'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheat_flags_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheat_flags_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheat_flags_user_id'), ['user_id'], unique=False)

    op.create_table('exam_questions',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['exam_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'question_id', name='uq_exam_question')
    )
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_questions_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_questions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_questions_section_id'), ['section_id'], unique=False)

    op.create_table('figure_translations',
    sa.Column('figure_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('figure_id', 'locale', name='uq_figure_locale')
    )
    with op.batch_alter_table('figure_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_figure_translations_figure_id'), ['figure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_figure_translations_locale'), ['locale'], unique=False)

    op.create_table('rating_changes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('rating_before', sa.Integer(), nullable=False),
    sa.Column('rating_after', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Float(), nullable=True),
    sa.Column('performance', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'attempt_id', name='uq_rating_change_attempt')
    )
    with op.batch_alter_table('rating_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_changes_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_changes_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_changes_user_id'), ['user_id'], unique=False)

    op.create_table('statement_translations',
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statement_id', 'locale', name='uq_statement_locale')
    )
    with op.batch_alter_table('statement_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statement_translations_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_statement_translations_statement_id'), ['statement_id'], unique=False)

    op.create_table('attempt_answers',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('exam_question_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('statement_count', sa.Integer(), nullable=False),
    sa.Column('awarded_points', sa.Float(), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('is_fully_correct', sa.Boolean(), nullable=False),
    sa.Column('per_statement_correct', sa.JSON(), nullable=False),
    sa.Column('seconds_spent', sa.Integer(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grader_id', sa.Integer(), nullable=True),
    sa.Column('grader_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_question_id'], ['exam_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grader_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_answers_exam_question_id'), ['exam_question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_answers_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_answers_exam_question_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_answers_attempt_id'))

    op.drop_table('attempt_answers')
    with op.batch_alter_table('statement_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statement_translations_statement_id'))
        batch_op.drop_index(batch_op.f('ix_statement_translations_locale'))

    op.drop_table('statement_translations')
    with op.batch_alter_table('rating_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_changes_user_id'))
        batch_op.drop_index(batch_op.f('ix_rating_changes_exam_id'))
        batch_op.drop_index(batch_op.f('ix_rating_changes_at'))

    op.drop_table('rating_changes')
    with op.batch_alter_table('figure_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_figure_translations_locale'))
        batch_op.drop_index(batch_op.f('ix_figure_translations_figure_id'))

    op.drop_table('figure_translations')
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_questions_section_id'))
        batch_op.drop_index(batch_op.f('ix_exam_questions_question_id'))
        batch_op.drop_index(batch_op.f('ix_exam_questions_exam_id'))

    op.drop_table('exam_questions')
    with op.batch_alter_table('cheat_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cheat_flags_user_id'))
        batch_op.drop_index(batch_op.f('ix_cheat_flags_status'))
        batch_op.drop_index(batch_op.f('ix_cheat_flags_severity'))
        batch_op.drop_index(batch_op.f('ix_cheat_flags_rule'))
        batch_op.drop_index(batch_op.f('ix_cheat_flags_exam_id'))
        batch_op.drop_index(batch_op.f('ix_cheat_flags_attempt_id'))

    op.drop_table('cheat_flags')
    with op.batch_alter_table('attempt_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_events_kind'))
        batch_op.drop_index(batch_op.f('ix_attempt_events_attempt_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_events_at'))

    op.drop_table('attempt_events')
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statements_question_id'))

    op.drop_table('statements')
    with op.batch_alter_table('question_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_translations_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_translations_locale'))

    op.drop_table('question_translations')
    with op.batch_alter_table('question_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_reviews_question_id'))

    op.drop_table('question_reviews')
    with op.batch_alter_table('figures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_figures_question_id'))

    op.drop_table('figures')
    with op.batch_alter_table('exam_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_statistics_exam_id'))

    op.drop_table('exam_statistics')
    with op.batch_alter_table('exam_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_sections_exam_id'))

    op.drop_table('exam_sections')
    with op.batch_alter_table('exam_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_enrollments_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_enrollments_exam_id'))

    op.drop_table('exam_enrollments')
    with op.batch_alter_table('exam_access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_access_grants_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_access_grants_exam_id'))

    op.drop_table('exam_access_grants')
    with op.batch_alter_table('exam_access_denials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_access_denials_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_access_denials_rule'))
        batch_op.drop_index(batch_op.f('ix_exam_access_denials_exam_id'))
        batch_op.drop_index(batch_op.f('ix_exam_access_denials_at'))

    op.drop_table('exam_access_denials')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_status'))
        batch_op.drop_index(batch_op.f('ix_attempts_risk_score'))
        batch_op.drop_index(batch_op.f('ix_attempts_rank'))
        batch_op.drop_index(batch_op.f('ix_attempts_is_flagged'))
        batch_op.drop_index(batch_op.f('ix_attempts_ip_address'))
        batch_op.drop_index(batch_op.f('ix_attempts_exam_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_device_fingerprint'))

    op.drop_table('attempts')
    with op.batch_alter_table('user_ip_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_ip_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_ip_links_ip_address'))

    op.drop_table('user_ip_links')
    with op.batch_alter_table('user_device_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_device_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_device_links_fingerprint'))

    op.drop_table('user_device_links')
    with op.batch_alter_table('topic_mastery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_mastery_user_id'))
        batch_op.drop_index(batch_op.f('ix_topic_mastery_topic_id'))

    op.drop_table('topic_mastery')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_questions_status'))
        batch_op.drop_index(batch_op.f('ix_questions_source_year'))
        batch_op.drop_index(batch_op.f('ix_questions_source_ref'))
        batch_op.drop_index(batch_op.f('ix_questions_question_type'))
        batch_op.drop_index(batch_op.f('ix_questions_is_official_ibo'))
        batch_op.drop_index(batch_op.f('ix_questions_author_id'))

    op.drop_table('questions')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_events_success'))
        batch_op.drop_index(batch_op.f('ix_login_events_ip_address'))
        batch_op.drop_index(batch_op.f('ix_login_events_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_login_events_email_attempted'))
        batch_op.drop_index(batch_op.f('ix_login_events_at'))

    op.drop_table('login_events')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_status'))
        batch_op.drop_index(batch_op.f('ix_exams_slug'))
        batch_op.drop_index(batch_op.f('ix_exams_opens_at'))
        batch_op.drop_index(batch_op.f('ix_exams_mode'))
        batch_op.drop_index(batch_op.f('ix_exams_closes_at'))

    op.drop_table('exams')
    with op.batch_alter_table('daily_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_activity_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_activity_day'))

    op.drop_table('daily_activity')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_registration_ip'))
        batch_op.drop_index(batch_op.f('ix_users_registration_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_users_rating'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('topic_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_translations_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topic_translations_locale'))

    op.drop_table('topic_translations')
    with op.batch_alter_table('ip_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_records_last_seen'))
        batch_op.drop_index(batch_op.f('ix_ip_records_is_blocked'))
        batch_op.drop_index(batch_op.f('ix_ip_records_is_allowlisted'))
        batch_op.drop_index(batch_op.f('ix_ip_records_ip_address'))

    op.drop_table('ip_records')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_slug'))

    op.drop_table('topics')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_region'))
        batch_op.drop_index(batch_op.f('ix_schools_name'))
        batch_op.drop_index(batch_op.f('ix_schools_city'))

    op.drop_table('schools')
    with op.batch_alter_table('device_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_records_last_seen'))
        batch_op.drop_index(batch_op.f('ix_device_records_fingerprint'))

    op.drop_table('device_records')
    # ### end Alembic commands ###
