"""Import every model so `Base.metadata` is complete before create_all/migrations."""
from app.models.analytics import (
    DailyActivity,
    ExamStatistics,
    RatingChange,
    TopicMastery,
)
from app.models.attempt import Attempt, AttemptAnswer, AttemptEvent
from app.models.content import (
    Figure,
    FigureTranslation,
    Question,
    QuestionReview,
    QuestionTranslation,
    Statement,
    StatementTranslation,
    Topic,
    TopicTranslation,
)
from app.models.enums import (
    AttemptStatus,
    Difficulty,
    EventKind,
    ExamMode,
    ExamStatus,
    FlagSeverity,
    FlagStatus,
    QuestionStatus,
    QuestionType,
    ReviewDecision,
    Role,
)
from app.models.exam import (
    DEFAULT_ANTICHEAT_POLICY,
    Exam,
    ExamEnrollment,
    ExamQuestion,
    ExamSection,
)
from app.models.security import (
    AuditLog,
    CheatFlag,
    DeviceRecord,
    ExamAccessDenial,
    ExamAccessGrant,
    IpRecord,
    LoginEvent,
    UserDeviceLink,
    UserIpLink,
)
from app.models.user import PasswordResetToken, School, User

__all__ = [
    "Attempt",
    "AttemptAnswer",
    "AttemptEvent",
    "AttemptStatus",
    "AuditLog",
    "CheatFlag",
    "DEFAULT_ANTICHEAT_POLICY",
    "DailyActivity",
    "DeviceRecord",
    "Difficulty",
    "EventKind",
    "Exam",
    "ExamAccessDenial",
    "ExamAccessGrant",
    "ExamEnrollment",
    "ExamMode",
    "ExamQuestion",
    "ExamSection",
    "ExamStatistics",
    "ExamStatus",
    "Figure",
    "FigureTranslation",
    "FlagSeverity",
    "FlagStatus",
    "IpRecord",
    "LoginEvent",
    "PasswordResetToken",
    "Question",
    "QuestionReview",
    "QuestionStatus",
    "QuestionTranslation",
    "QuestionType",
    "RatingChange",
    "ReviewDecision",
    "Role",
    "School",
    "Statement",
    "StatementTranslation",
    "Topic",
    "TopicMastery",
    "TopicTranslation",
    "User",
    "UserDeviceLink",
    "UserIpLink",
]
